var exercises = [
"4-Way Neck",
"Neck PushUp",
"Manual Neck",
"Bench Press",
"Deadlift",
"Dumbbell Bench Press",
"Decline Bench Press",
"Dumbbell Decline Bench Press",
"Incline Bench Press",
"Dumbbell Incline Bench Press",
"Chest Fly",
"Incline Chest Fly",
"Decline Chest Fly",
"Push Up",
"Incline PushUp",
"Decline PushUp",
"Wide-Grip PushUp",
"Military Press",
"Behind-Neck Press",
"Push Press",
"Pulldown",
"Lateral Raise",
"Internal Rotator Cuff",
"External Rotator Cuff",
"Front Raise",
"Pull-Over",
"Barbell Shoulder Shrug",
"Dumbbell Shoulder Shrug",
"Cable Shoulder Shrug",
"Upright Row",
"Cable Upright Row",
"Arnold Press",
"Shoulder Press",
"Clean Pull",
"Split Jerk",
"Jerk",
"Power Clean",
"Barbell Shoulder Press",
"Barbell Row",
"Tricep Kickback",
"Barbell Tricep Extension",
"Dumbbell Tricep Extension",
"Tricep Pushdown",
"Close-Grip Bench Press",
"Reverse Grip Bench Press",
"Dip",
"Press/Tricep Extension",
"One-Arm Dumbbell French Press",
"Dumbbell French Press",
"Barbell French Press",
"Barbell Curl",
"Dumbbell Curl",
"Preacher Curl",
"One-Arm Preacher Curl",
"Hammer Curl",
"Concentration Curl",
"Incline Dumbbell Curl",
"Reverse Barbell Curl",
"Reverse Dumbbell Curl",
"Forearm Dumbbell Curl",
"Forearm Barbell Curl",
"Forearm Dumbbell Extension",
"Forearm Barbell Extension",
"Back Extension",
"Good Morning",
"Romanian Deadlift",
"Stiff-Legged Deadlift",
"T-Bar Row",
"Bent-Over Barbell Row",
"Dumbbell Row",
"One-Arm Dumbbell Row",
"Wide-Grip Pulldown",
"Reverse-Grip Pulldown",
"Close-Grip Pulldown",
"Behind-Neck Pulldown",
"Reverse-Grip Lat Pulldown",
"Cable Row",
"Pull-Up",
"Wide-Grip Pull-Up",
"Behind-Neck Pull-Up",
"Close-Grip Pull-Up",
"SitUp",
"Crunch",
"Jackknife",
"Ab Machine",
"Raised-Leg Crunch",
"Reverse Trunk Twist",
"Hip Thrust",
"Ab Wheel",
"Side Crunch",
"Russian Twist",
"Hanging Leg Raise",
"Superman",
"Flutter Kick",
"Medicine Ball Crunch",
"Decline Crunch",
"Crunches",
"Toe Touch",
"Crossover Crunch",
"Oblique Crunch",
"Dumbbell Side Bend",
"Oblique Twist",
"Dip Bar Leg Raise",
"V-Spread Toe Touches",
"High-bar Squat",
"Low-bar Squat",
"Front Squat",
"Box Squat",
"Hack Squat",
"Jump Squat",
"Sumo Squat",
"One-Arm Overhead Dumbbell Squat",
"Narrow Dumbbell Squat",
"Leg Press",
"Single-Leg Leg Press",
"Leg Curl",
"Unilateral Leg Curl",
"Leg Extension",
"Unilateral Leg Extension",
"Dumbbell Lunge",
"Barbell Lunge",
"Dumbbell Walking Lunge",
"Barbell Walking Lunge",
"Glute/Ham Raise",
"Step-Up",
"Box Jump",
"Wall Sit",
"Glute/Ham Raise",
"Standing Calf Raise",
"Single-Leg Standing Calf Raise",
"Leg Press Calf Raise",
"Barbell Calf Raise",
"Dumbbell Calf Raise",
"Seated Calf Raise",
 
]